services:
  - type: static
    name: tactical-control-dashboard-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: ""
